@startuml

skinparam componentStyle uml2

package "'ResourceOrchestration' Aggregate" <<Rectangle>> {
	class CommunicationIntermediary <<(A,#fffab8) Aggregate Root>> {
		String actors
		String resources
		ImmigrationAuthorityServiceExchange regulatoryData
		ServiceProviderServiceExchange businessData
		TravelerServiceExchange travelerData
		MedicalServiceProviderServiceExchange healthData
		void resourceOrchestration()
		void actorOrchestration()
		void e2eEncryption()
		void security()
	}
}


@enduml
