@startuml

skinparam componentStyle uml2

package "'MedicalServiceProviderContext' Aggregate" <<Rectangle>> {
	class MedicalServiceProviderContext <<(A,#fffab8) Aggregate Root>> {
		MedicalServiceProviderChracteristics institutionalData
		OrganizationalNeeds patientData
		MedicalServiceProviderValueExpectation invoke()
		MedicalServiceProviderCustomerJourney provideData()
		MedicalServiceProviderCustomerJourney informEngagementDesign()
	}
	class MedicalServiceProviderChracteristics <<(E,DarkSeaGreen) Entity>> {
		String testCenterLocation
		String testResults
		String patienVaccinationStatus
		MedicalServiceProviderContext inform()
	}
	class OrganizationalNeeds <<(E,DarkSeaGreen) Entity>> {
		String patientPersonalData
		String patientHealthData
		String patientDataDistribution
		MedicalServiceProviderContext inform()
	}
}
MedicalServiceProviderContext --> MedicalServiceProviderChracteristics : institutionalData
MedicalServiceProviderContext --> OrganizationalNeeds : patientData


@enduml
