@startuml

skinparam componentStyle uml2

package "'MedicalServiceProviderCustomerJourney' Aggregate" <<Rectangle>> {
	class MedicalServiceProviderServiceForServiceExchange <<(A,#fffab8) Aggregate Root>> {
		String valueExperience
		MedicalServiceProviderContext engagementPreferences
		MedicalServiceProviderValueExpectation expecations
		MedicalServiceProviderResourceIntegration healthData
		MedicalServiceProviderResourceExchange externalData
		void personalResourceIntegration()
		void externalResourceConsumption()
		void valueCocreation()
	}
	class MedicalServiceProviderResourceIntegration <<(V,DarkSeaGreen) Value Object>> {
		String locationData
		String patientPersonalData
		String patientHealthData
		String patientTestResults
		MedicalServiceProviderEngagementDesign customerJourney
		void provideHealthData()
	}
	class MedicalServiceProviderEngagementDesign <<(E,DarkSeaGreen) Entity>> {
		String existingTestProcedures
		String existingDataDistributionPatterns
		MedicalServiceProviderResourceIntegration integrateResources()
		MedicalServiceProviderResourceExchange enableResourceExchange()
	}
	class MedicalServiceProviderResourceExchange <<(E,DarkSeaGreen) Entity>> {
		String patientPersonalData
		String regulatoryData
		MedicalServiceProviderEngagementDesign externalResourceAccess
		void integrateExternalResources()
	}
}
MedicalServiceProviderServiceForServiceExchange --> MedicalServiceProviderResourceIntegration : healthData
MedicalServiceProviderServiceForServiceExchange --> MedicalServiceProviderResourceExchange : externalData
MedicalServiceProviderResourceIntegration --> MedicalServiceProviderEngagementDesign : customerJourney
MedicalServiceProviderResourceExchange --> MedicalServiceProviderEngagementDesign : externalResourceAccess


@enduml
