@startuml

skinparam componentStyle uml2

package "'MedicalServiceProviderValueSpace' Aggregate" <<Rectangle>> {
	class SimplyGoValueProposition4 <<(E,DarkSeaGreen) Entity>> {
		String travelerPersonalData
		String travelerHealthData
		MedicalServiceProviderValueExpectation inspiration
		MedicalServiceProviderValueExpectation proposeSolutions()
	}
	class MedicalServiceProviderValueExpectation <<(A,#fffab8) Aggregate Root>> {
		String globalDataDistribution
		String multilingualAccess
		String operationEfficiency
		MedicalServiceProviderContext organizationalNeeds
		SimplyGoValueProposition4 valueProposition
		SimplyGoValueProposition4 openSolutionSpace()
		MedicalServiceProviderEngagementDesign dictate()
	}
}
SimplyGoValueProposition4 --> MedicalServiceProviderValueExpectation : inspiration
MedicalServiceProviderValueExpectation --> SimplyGoValueProposition4 : valueProposition


@enduml
