@startuml

skinparam componentStyle uml2

package "'ValueSpaceServiceProvider' Aggregate" <<Rectangle>> {
	class SimplyGoValueProposition1 <<(E,DarkSeaGreen) Entity>> {
		String legalCompliance
		String businessOperation
		ServiceProviderValueExpectation inspiration
		ServiceProviderValueExpectation proposeSolutions()
	}
	class ServiceProviderValueExpectation <<(A,#fffab8) Aggregate Root>> {
		String profit
		String businessOperation
		ServiceProviderContext businessNeeds
		SimplyGoValueProposition1 valueProposition
		SimplyGoValueProposition1 openSolutionSpace()
		ServiceProviderEngagementDesign dictate()
	}
}
SimplyGoValueProposition1 --> ServiceProviderValueExpectation : inspiration
ServiceProviderValueExpectation --> SimplyGoValueProposition1 : valueProposition


@enduml
