@startuml

skinparam componentStyle uml2

package "'InfluencialDynamics' Aggregate" <<Rectangle>> {
	class MarketContext <<(A,#fffab8) Aggregate Root>> {
		String serviceEcoystemEnvironment
		CulturalContexts culturalDesignAspects
		TechnologicalTrends technologicalInfluence
		EconomicalTrends economicAndLegalInfluence
		serviceSystem influenceDesign()
	}
	class CulturalContexts <<(E,DarkSeaGreen) Entity>> {
		String ageGroupSpecifics
		String ethicalConventions
		String languages
		MarketContext shapeSpecifics()
	}
	class TechnologicalTrends <<(E,DarkSeaGreen) Entity>> {
		String trends
		String standards
		String norms
		MarketContext frameSolutionSpace()
	}
	class EconomicalTrends <<(E,DarkSeaGreen) Entity>> {
		String covid19
		String legalActions
		String changingConsumerBehavior
		MarketContext frameSolutionSpace()
	}
}
MarketContext --> CulturalContexts : culturalDesignAspects
MarketContext --> TechnologicalTrends : technologicalInfluence
MarketContext --> EconomicalTrends : economicAndLegalInfluence
legend left
  This bounded context implements the subdomain 'MarketEnvironmentDomain'.
end legend


@enduml
