@startuml

skinparam componentStyle uml2

package "'TravelerCustomerJourney' Aggregate" <<Rectangle>> {
	class TravelerServiceforServiceExchange <<(A,#fffab8) Aggregate Root>> {
		String serviceExperience
		TravelerContext engagementPreferences
		TravelerValueExpectation expectations
		TravelerResourceIntegration travelerData
		TravelerResourceExchange externalData
		void personalResourceIntegration()
		void externalResourceConsumption()
		void valueCocreation()
	}
	class TravelerResourceIntegration <<(V,DarkSeaGreen) Value Object>> {
		String personalData
		String healthData
		String tripData
		TravelerEngagementDesign customerJourney
		void provideTravelerData()
	}
	class TravelerEngagementDesign <<(E,DarkSeaGreen) Entity>> {
		String mobileApp
		String browser
		String onlineBookingPattern
		TravelerResourceIntegration integrateResources()
		TravelerResourceExchange enableResourceExchange()
	}
	class TravelerResourceExchange <<(E,DarkSeaGreen) Entity>> {
		String entryRegulations
		String healthCare
		String services
		TravelerEngagementDesign externalResourceAccess
		void integrateExternalResources()
	}
}
TravelerServiceforServiceExchange --> TravelerResourceIntegration : travelerData
TravelerServiceforServiceExchange --> TravelerResourceExchange : externalData
TravelerResourceIntegration --> TravelerEngagementDesign : customerJourney
TravelerResourceExchange --> TravelerEngagementDesign : externalResourceAccess


@enduml
