@startuml

skinparam componentStyle uml2

package "'MedicalServiceProviderEngagement' Aggregate" <<Rectangle>> {
	class MedicalServiceProviderCustomerJourney <<(V,DarkSeaGreen) Value Object>> {
		String travelerPreferredTouchpoints
		String travelerEngagementPatterns
		MedicalServiceProviderServiceExchange provideTouchpoints()
	}
	class MedicalServiceProviderServiceExchange <<(A,#fffab8) Aggregate Root>> {
		String resourceIntegration
		String externalDataAccess
		MedicalServiceProviderCustomerJourney interaction
		CommunicationIntermediary externalData
		CommunicationIntermediary resourceIntegration()
	}
}
MedicalServiceProviderServiceExchange --> MedicalServiceProviderCustomerJourney : interaction


@enduml
