@startuml

skinparam componentStyle uml2

package "'ImmigrationAuthorityEngagement' Aggregate" <<Rectangle>> {
	class ImmigrationAuthorityCustomerJourney <<(E,DarkSeaGreen) Entity>> {
		String travelerPreferredTouchpoints
		String travelerEngagementPatterns
		ImmigrationAuthorityServiceExchange interaction
		ImmigrationAuthorityServiceExchange provideTouchpoints()
	}
	class ImmigrationAuthorityServiceExchange <<(A,#fffab8) Aggregate Root>> {
		String resourceIntegration
		String externalDataAccess
		CommunicationIntermediary immigrationAuthorityData
		CommunicationIntermediary resourceIntegration()
	}
}
ImmigrationAuthorityCustomerJourney --> ImmigrationAuthorityServiceExchange : interaction


@enduml
