@startuml

skinparam componentStyle uml2

package "'ValueSpaceTraveler' Aggregate" <<Rectangle>> {
	class SimplyGoValueProposition2 <<(V,DarkSeaGreen) Value Object>> {
		String healthCare
		String travel
		String immigration
		TravelerValueExpectation inspiration
		TravelerValueExpectation proposeSolutions()
	}
	class TravelerValueExpectation <<(A,#fffab8) Aggregate Root>> {
		String healthServices
		String freeTravel
		String serviceConsume
		TravelerContext personalNeeds
		SimplyGoValueProposition2 valueProposition
		SimplyGoValueProposition2 openSolutionSpace()
		ServiceProviderEngagementDesign dictate()
	}
}
SimplyGoValueProposition2 --> TravelerValueExpectation : inspiration
TravelerValueExpectation --> SimplyGoValueProposition2 : valueProposition


@enduml
