@startuml

skinparam componentStyle uml2

package "'ImmigrationAuthorityContext' Aggregate" <<Rectangle>> {
	class ImmigrationAuthorityContext <<(A,#fffab8) Aggregate Root>> {
		RegulatoryNeeds regulatoryNeeds
		ImmigrationauthorityCharacteristics regulatoryData
		ImmigrationAuthorityValueExpectation invoke()
		ImmigrationAuthorityCustomerJourney provideData()
		ImmigrationAuthorityCustomerJourney informEngagementDesign()
	}
	class ImmigrationauthorityCharacteristics <<(E,DarkSeaGreen) Entity>> {
		String entryRegulations
		String entryProcedures
		ImmigrationAuthorityContext impact()
	}
	class RegulatoryNeeds <<(E,DarkSeaGreen) Entity>> {
		String travelerData
		String distributionOfNewsandInfos
		ImmigrationAuthorityContext inform()
	}
}
ImmigrationAuthorityContext --> RegulatoryNeeds : regulatoryNeeds
ImmigrationAuthorityContext --> ImmigrationauthorityCharacteristics : regulatoryData


@enduml
