@startuml

skinparam componentStyle uml2

package "'ServiceProviderEngagement' Aggregate" <<Rectangle>> {
	class ServiceProviderCustomerJourney <<(V,DarkSeaGreen) Value Object>> {
		String travelerPreferredTouchpoints
		String travelerEngagementPatterns
		ServieProviderServiceExchange provideTouchpoints()
	}
	class ServiceProviderServiceExchange <<(A,#fffab8) Aggregate Root>> {
		String resourceIntegration
		String externalDataAccess
		ServiceProviderCustomerJourney interaction
		CommunicationIntermediary externalData
		CommunicationIntermediary resourceIntegration()
	}
}
ServiceProviderServiceExchange --> ServiceProviderCustomerJourney : interaction


@enduml
