@startuml

skinparam componentStyle uml2

package "'ServiceProviderCustomerJourney' Aggregate" <<Rectangle>> {
	class ServiceProviderServiceForServiceExchange <<(A,#fffab8) Aggregate Root>> {
		String serviceExperience
		ServiceProviderValueExpectation expectations
		ServiceProviderContext engagementPreferences
		ServiceProviderResourceIntegration businessData
		ServiceProviderResourceExchange externalData
	}
	class ServiceProviderResourceIntegration <<(V,DarkSeaGreen) Value Object>> {
		String businessData
		String customerData
		ServiceProviderEngagementDesign customerJourney
		provide businessData()
	}
	class ServiceProviderEngagementDesign <<(E,DarkSeaGreen) Entity>> {
		String mobileApp
		ServiceProviderResourceIntegration integrateResources()
		ServiceProviderResourceExchange enableResourceExchange()
	}
	class ServiceProviderResourceExchange <<(E,DarkSeaGreen) Entity>> {
		String customerData
		String legalObligations
		ServiceProviderEngagementDesign externalResourceAccess
		void integrateExternalResources()
	}
}
ServiceProviderServiceForServiceExchange --> ServiceProviderResourceIntegration : businessData
ServiceProviderServiceForServiceExchange --> ServiceProviderResourceExchange : externalData
ServiceProviderResourceIntegration --> ServiceProviderEngagementDesign : customerJourney
ServiceProviderResourceExchange --> ServiceProviderEngagementDesign : externalResourceAccess


@enduml
