@startuml

skinparam componentStyle uml2

package "'ImmigrationAuthorityContext' Aggregate" <<Rectangle>> {
	class ImmigrationAuthorityContext <<(A,#fffab8) Aggregate Root>> {
		ImmigrationAuthorityValueExpectation regulatoryNeeds
		ImmigrationAuthorityEngagementDesign engagementPreferences
		ImmigrationAuthorityValueExpectation invoke()
		ImmigrationAuthorityCustomerJourney provideData()
		ImmigrationAuthorityCustomerJourney informEngagementDesign()
	}
	class ImmigrationauthorityCharacteristics <<(E,DarkSeaGreen) Entity>> {
		String entryRegulations
		String entryProcedures
		ImmigrationAuthorityContext regulatoryData
		ImmigrationAuthorityContext impact()
	}
	class RegulatoryNeeds <<(E,DarkSeaGreen) Entity>> {
		String travelerData
		String distributionOfNewsandInfos
		ImmigrationAuthorityContext regulatoryNeeds
		ImmigrationAuthorityContext inform()
	}
}
ImmigrationauthorityCharacteristics --> ImmigrationAuthorityContext : regulatoryData
RegulatoryNeeds --> ImmigrationAuthorityContext : regulatoryNeeds


@enduml
