@startuml

skinparam componentStyle uml2

package "'TravelerContext' Aggregate" <<Rectangle>> {
	class TravelerContext <<(A,#fffab8) Aggregate Root>> {
		TargetSegments segmentSpecifications
		IndividualCharacteristics individualData
		TravelerValueExpectation invoke()
		TravelerCustomerJourney provideData()
		TravelerCustomerJourney informEngagementDesign()
	}
	class TargetSegments <<(E,DarkSeaGreen) Entity>> {
		String painsAndGains
		String serviceRequirements
		String demographics
		String typicalBehaviors
		TravelerContext frame()
	}
	class IndividualCharacteristics <<(E,DarkSeaGreen) Entity>> {
		String personalData
		String healthData
		String tripData
		TravelerContext provideData()
	}
}
TravelerContext --> TargetSegments : segmentSpecifications
TravelerContext --> IndividualCharacteristics : individualData


@enduml
