@startuml

skinparam componentStyle uml2

package "'ResourceIntegration' Aggregate" <<Rectangle>> {
	class PassengerData <<(E,DarkSeaGreen) Entity>> {
		String personalData
		String healthData
	}
	class DataProvision <<(A,#fffab8) Aggregate Root>> {
		String sitaAirportNetwork
		PassengerData passengerData
		ImmigrationAuthority transmittPassengerData()
	}
}
DataProvision --> PassengerData : passengerData
legend left
  This bounded context implements the subdomain 'SITADomain'.
end legend


@enduml
