@startuml

skinparam componentStyle uml2

package "'TravelerEngagement' Aggregate" <<Rectangle>> {
	class TravelerCustomerJourney <<(E,DarkSeaGreen) Entity>> {
		String travelerPreferredTouchpoints
		String travelerEngagementPatterns
		TravelerServiceExchange interaction
		TravelerServiceExchange provideTouchpoints()
	}
	class TravelerServiceExchange <<(A,#fffab8) Aggregate Root>> {
		String resourceIntegration
		String externalDataAccess
		CommunicationIntermediary travelerData
		CommunicationIntermediary resourceIntegration()
	}
}
TravelerCustomerJourney --> TravelerServiceExchange : interaction


@enduml
