@startuml

skinparam componentStyle uml2

package "'MedicalServiceProviderCustomerJourney' Aggregate" <<Rectangle>> {
	class MedicalServiceProviderEngagementDesign <<(A,#fffab8) Aggregate Root>> {
		String existingTestProcedures
		String existingDataDistributionPatterns
		MedicalServiceProviderResourceIntegration regulatoryData
		MedicalServiceProviderResourceExchange accessPoints
		MedicalServiceProviderResourceIntegration integrateResources()
		MedicalServiceProviderResourceExchange enableResourceExchange()
	}
	class MedicalServiceProviderResourceIntegration <<(E,DarkSeaGreen) Entity>> {
		String locationData
		String patientPersonalData
		String patientHealthData
		String patientTestResults
		MedicalServiceProviderValueCocreation ownContribution
	}
	class MedicalServiceProviderResourceExchange <<(E,DarkSeaGreen) Entity>> {
		String patientPersonalData
		String regulatoryData
		MedicalServiceProviderValueCocreation externalContribution
	}
	class MedicalServiceProviderValueCocreation <<(V,DarkSeaGreen) Value Object>> {
		String seamlessDataExchange
		String improvedEfficiency
		String improvedEffectiveness
		void valueInUse()
	}
}
MedicalServiceProviderEngagementDesign --> MedicalServiceProviderResourceIntegration : regulatoryData
MedicalServiceProviderEngagementDesign --> MedicalServiceProviderResourceExchange : accessPoints
MedicalServiceProviderResourceIntegration --> MedicalServiceProviderValueCocreation : ownContribution
MedicalServiceProviderResourceExchange --> MedicalServiceProviderValueCocreation : externalContribution


@enduml
