@startuml

skinparam componentStyle uml2

package "'SITA' Aggregate" <<Rectangle>> {
	class SITAPlatform <<(A,#fffab8) Aggregate Root>> {
		passengerData
		CommunicationIntermediary passengerData
		ImmigrationAuthorityEngagement forwardData()
	}
}
package "'ResourceOrchestration' Aggregate" <<Rectangle>> {
	class CommunicationIntermediary <<(A,#fffab8) Aggregate Root>> {
		actors
		resources
		ImmigrationAuthorityServiceExchange regulatoryData
		ServiceProviderServiceExchange businessData
		TravelerServiceExchange travelerData
		MedicalServiceProviderServiceExchange healthData
		void resourceOrchestration()
		void actorOrchestration()
		void e2eEncryption()
		void security()
	}
}
package "'ImmigrationAuthorityEngagement' Aggregate" <<Rectangle>> {
	class ImmigrationAuthorityCustomerJourney <<(V,DarkSeaGreen) Value Object>> {
		travelerPreferredTouchpoints
		travelerEngagementPatterns
		ImmigrationAuthorityServiceExchange provideTouchpoints()
	}
	class ImmigrationAuthorityServiceExchange <<(A,#fffab8) Aggregate Root>> {
		resourceIntegration
		externalDataAccess
		ImmigrationAuthorityCustomerJourney interaction
		CommunicationIntermediary externalData
		SITAPlatform passengerData
		CommunicationIntermediary resourceIntegration()
	}
}
package "'ServiceProviderEngagement' Aggregate" <<Rectangle>> {
	class ServiceProviderCustomerJourney <<(V,DarkSeaGreen) Value Object>> {
		travelerPreferredTouchpoints
		travelerEngagementPatterns
		ServieProviderServiceExchange provideTouchpoints()
	}
	class ServiceProviderServiceExchange <<(A,#fffab8) Aggregate Root>> {
		resourceIntegration
		externalDataAccess
		ServiceProviderCustomerJourney interaction
		CommunicationIntermediary externalData
		CommunicationIntermediary resourceIntegration()
	}
}
package "'TravelerEngagement' Aggregate" <<Rectangle>> {
	class TravelerCustomerJourney <<(V,DarkSeaGreen) Value Object>> {
		travelerPreferredTouchpoints
		travelerEngagementPatterns
		TravelerServiceExchange provideTouchpoints()
	}
	class TravelerServiceExchange <<(A,#fffab8) Aggregate Root>> {
		resourceIntegration
		externalDataAccess
		TravelerCustomerJourney interaction
		CommunicationIntermediary externalData
		CommunicationIntermediary resourceIntegration()
	}
}
package "'MedicalServiceProviderEngagement' Aggregate" <<Rectangle>> {
	class MedicalServiceProviderCustomerJourney <<(V,DarkSeaGreen) Value Object>> {
		travelerPreferredTouchpoints
		travelerEngagementPatterns
		MedicalServiceProviderServiceExchange provideTouchpoints()
	}
	class MedicalServiceProviderServiceExchange <<(A,#fffab8) Aggregate Root>> {
		resourceIntegration
		externalDataAccess
		MedicalServiceProviderCustomerJourney interaction
		CommunicationIntermediary externalData
		CommunicationIntermediary resourceIntegration()
	}
}
SITAPlatform --> CommunicationIntermediary : passengerData
CommunicationIntermediary --> ImmigrationAuthorityServiceExchange : regulatoryData
CommunicationIntermediary --> ServiceProviderServiceExchange : businessData
CommunicationIntermediary --> TravelerServiceExchange : travelerData
CommunicationIntermediary --> MedicalServiceProviderServiceExchange : healthData
ImmigrationAuthorityServiceExchange --> ImmigrationAuthorityCustomerJourney : interaction
ImmigrationAuthorityServiceExchange --> CommunicationIntermediary : externalData
ImmigrationAuthorityServiceExchange --> SITAPlatform : passengerData
ServiceProviderServiceExchange --> ServiceProviderCustomerJourney : interaction
ServiceProviderServiceExchange --> CommunicationIntermediary : externalData
TravelerServiceExchange --> TravelerCustomerJourney : interaction
TravelerServiceExchange --> CommunicationIntermediary : externalData
MedicalServiceProviderServiceExchange --> MedicalServiceProviderCustomerJourney : interaction
MedicalServiceProviderServiceExchange --> CommunicationIntermediary : externalData
legend left
  This bounded context implements the subdomain 'SimplyGoPlatformDomain'.
end legend


@enduml
