@startuml

skinparam componentStyle uml2

package "'TravelerEngagement' Aggregate" <<Rectangle>> {
	class TravelerCustomerJourney <<(V,DarkSeaGreen) Value Object>> {
		String travelerPreferredTouchpoints
		String travelerEngagementPatterns
		TravelerServiceExchange provideTouchpoints()
	}
	class TravelerServiceExchange <<(A,#fffab8) Aggregate Root>> {
		String resourceIntegration
		String externalDataAccess
		TravelerCustomerJourney interaction
		CommunicationIntermediary externalData
		CommunicationIntermediary resourceIntegration()
	}
}
TravelerServiceExchange --> TravelerCustomerJourney : interaction


@enduml
