@startuml

skinparam componentStyle uml2

package "'ResourceOrchestration' Aggregate" <<Rectangle>> {
	class CommunicationIntermediary <<(A,#fffab8) Aggregate Root>> {
		String actors
		String resources
		TravelerServiceExchange externalData
		MedicalServiceProviderServiceExchange externalData
		ImmigrationAuthorityServiceExchange externalData
		ServiceProviderServiceExchange externalData
		SITAPlatform passengerData
		void resourceOrchestration()
		void actorOrchestration()
		void e2eEncryption()
		void security()
	}
}


@enduml
