@startuml

skinparam componentStyle uml2

package "'ImmigrationAuthorityEngagement' Aggregate" <<Rectangle>> {
	class ImmigrationAuthorityCustomerJourney <<(V,DarkSeaGreen) Value Object>> {
		String travelerPreferredTouchpoints
		String travelerEngagementPatterns
		ImmigrationAuthorityServiceExchange provideTouchpoints()
	}
	class ImmigrationAuthorityServiceExchange <<(A,#fffab8) Aggregate Root>> {
		String resourceIntegration
		String externalDataAccess
		ImmigrationAuthorityCustomerJourney interaction
		CommunicationIntermediary externalData
		SITAPlatform passengerData
		CommunicationIntermediary resourceIntegration()
	}
}
ImmigrationAuthorityServiceExchange --> ImmigrationAuthorityCustomerJourney : interaction


@enduml
