@startuml

skinparam componentStyle uml2

package "'SITA' Aggregate" <<Rectangle>> {
	class SITAPlatform <<(A,#fffab8) Aggregate Root>> {
		String passengerData
		CommunicationIntermediary passengerData
		ImmigrationAuthorityEngagement forwardData()
	}
}


@enduml
